name: Publish Python package

on:
  release:
    types:
      - published

permissions: {}

jobs:
  build:
    name: build
    permissions:
      contents: read
    uses: eserie-fox/github-workflows/.github/workflows/python-build.yml@main

  publish:
    name: publish
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
